### PR TITLE
Add Neos 4 compatibility, smaller improvements

### PR DESCRIPTION
**Pull request by danielkestler**
Adds Neos 4 in composer.json, adds setting "isPaginated" for presets to control pagination / loading and style the flat nav to look more like the Neos page tree (paddings, colors).

This is my first React contribution (and programming) ever, hope I did it right.

### CODE REVIEW

**Comment by danielkestler** [comment]
Hi, of course. Here are the changes in detail:

1. Neos 4 compatibility by adding version number to composer.json
2. Preset-setting "isPaginated" to show or hide the reload-button if you don't want a paginated list
3. Styling improvement of the flat nav, see screenshots:

before
after

**Comment by dimaip** [comment]
Hey, sorry for slow response. Shouldn't `isPaginated` be set to true by default? Otherwise it would be a breaking change.

**Comment by danielkestler** [comment]
Oh, you're right, it should. But I did not find the part where to do this ... it is probably somewhere in these setState()-calls?

**Comment by dimaip** [comment]
No no it's enough to just add it to Settings.yaml

**Comment by dimaip** [comment]
Ah, sorry, I see that it's preset based. In this case I propose to rename it to `disablePagination: true`.

**Comment by danielkestler** [comment]
Great idea, changed it accordingly.

**Comment by dimaip** [comment]
Thanks a lot for the contribution, love it!

**Comment by danielkestler** [comment]
Great, you're welcome. Any reasons there is no release on packagist?

**Comment by dimaip** [comment]
Just did.

**Pull request merged**
