### PR TITLE
BUGFIX: added id to TabPanel and changed tabs__content height

### PR DESCRIPTION
**Pull request by pmaas**
Fix for https://github.com/psmb/Psmb.FlatNav/issues/18

### CODE REVIEW

**Comment by Sebobo** [comment]
I still don't get full height when the content tree is minimized.

**Comment by pmaas** [comment]
> I still don't get full height when the content tree is minimized.

Hm, I think it's just the background of the page tree, wich isn't expanded to the full height, right? I would try to fix this together wir #2. Or do you mean the content of the page tree?

**Comment by Sebobo** [comment]
Yes it's just the background :) Thanks!

**Comment by pmaas** [comment]
@Sebobo the background height bug is fixed with https://github.com/psmb/Psmb.FlatNav/pull/20

**Pull request merged**
